spring:
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_boot_audit
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update  # Can be "none", "update", "create", or "create-drop"
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        format_sql: true
    open-in-view: false  # Optional, for controlling lazy loading



audit:
  service: true             # IS SERVICE ARE AUDITABLE
  repository: true          # IS REPOSITORY ARE AUDITABLE
  controller: true          # IS CONTROLLER ARE AUDITABLE
  exception: true          # IS EXCEPTION ARE AUDITABLE
  component: true          # IS COMPONENT ARE AUDITABLE
  strategy: logFile
  async : true
  application-name: e-commerce
  application-version: 1.0.0


logging:
  file:
    name: C://logs//application.log


