spring:
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_boot_audit
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none # Can be "none", "update", "create", or "create-drop"
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        format_sql: false
    open-in-view: false  # Optional, for controlling lazy loading
  batch:
    jdbc:
      initialize-schema: always

audit:
  chunkSize : 200000
scheduler:
  persist-log-dump-rate: 20000